pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t imdbdata .'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker run -p 8081:9090 imdbdata'
            }
        }
    }
}
